apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-dmi-stub-1
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: dmi-stub
spec:
  replicas: {{ .Values.dmiStub.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cps-and-ncmp.name" . }}
      component: dmi-stub
      instance: dmi-stub-1
  template:
    metadata:
      labels:
        app: {{ include "cps-and-ncmp.name" . }}
        component: dmi-stub
        instance: dmi-stub-1
    spec:
      containers:
        - name: dmi-stub
          image: "{{ .Values.dmiStub.image.repository }}:{{ .Values.dmiStub.image.tag }}"
          imagePullPolicy: {{ .Values.dmiStub.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.dmiStub.deployment1.containerPort }}
          env:
            {{- range $key, $value := .Values.dmiStub.env }}
            - name: {{ $key | upper }}
              value: "{{ $value }}"
            {{- end }}
            - name: DMI_SERVER_PORT
              value: "{{ .Values.dmiStub.deployment1.containerPort }}"
          resources:
            {{- toYaml .Values.dmiStub.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.dmiStub.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.dmiStub.readinessProbe | nindent 12 }}