{{- if .Values.dmiStub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cps-and-ncmp.fullname" . }}-dmi-stub-2
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: dmi-stub
spec:
  replicas: {{ .Values.dmiStub.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cps-and-ncmp.name" . }}
      component: dmi-stub
      instance: dmi-stub-2
  template:
    metadata:
      labels:
        app: {{ include "cps-and-ncmp.name" . }}
        component: dmi-stub
        instance: dmi-stub-2
    spec:
      containers:
        - name: dmi-stub
          image: "{{ .Values.dmiStub.image.repository }}:{{ .Values.dmiStub.image.tag }}"
          imagePullPolicy: {{ .Values.dmiStub.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.dmiStub.deployment2.containerPort }}
          env:
            - name: DMI_STUB_SERVER_PORT
              value: "{{ .Values.dmiStub.deployment2.containerPort }}"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            {{- range $key, $value := .Values.dmiStub.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.dmiStub.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.dmiStub.deployment2.containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.dmiStub.deployment2.containerPort }}
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
{{- end }}